### get my info
GET http://localhost:3000/api/student/user HTTP/1.1
content-type: application/json
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE2NzUyNDM0MjQsImV4cCI6MTY3NTI0NzAyNH0.j-rdLw3gb9OuOMGbpct8wqnwFV3jkPlFPRhIotIPZtg

